#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPAppendDocument
@end

@interface ASPAppendDocument : ASPObject


@property(nonatomic) NSString* document;

@property(nonatomic) NSNumber* startPage;

@property(nonatomic) NSNumber* endPage;

@end
