#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"
#import "ASPColor.h"


@protocol ASPAnnotation
@end

@interface ASPAnnotation : ASPObject


@property(nonatomic) ASPColor* color;

@property(nonatomic) NSString* contents;

@property(nonatomic) NSString* creationDate;

@property(nonatomic) NSString* subject;

@property(nonatomic) NSString* title;

@property(nonatomic) NSString* modified;

@property(nonatomic) NSArray<ASPLink>* links;

@end
