#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPPages.h"
#import "ASPDocumentProperties.h"
#import "ASPLink.h"


@protocol ASPDocument
@end

@interface ASPDocument : ASPObject


@property(nonatomic) ASPDocumentProperties* documentProperties;

@property(nonatomic) ASPPages* pages;

@property(nonatomic) NSArray<ASPLink>* links;

@end
