#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPField.h"


@protocol ASPFieldResponse
@end

@interface ASPFieldResponse : ASPObject


@property(nonatomic) ASPField* field;

@property(nonatomic) NSString* code;

@property(nonatomic) NSString* status;

@end
