#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"
#import "ASPRectangle.h"


@protocol ASPField
@end

@interface ASPField : ASPObject


@property(nonatomic) NSString* name;

@property(nonatomic) NSString* type;

@property(nonatomic) NSArray* /* NSString */ values;

@property(nonatomic) NSArray* /* NSNumber */ selectedItems;

@property(nonatomic) ASPRectangle* rect;

@property(nonatomic) NSArray<ASPLink>* links;

@end
