#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPPageWordCount
@end

@interface ASPPageWordCount : ASPObject


@property(nonatomic) NSNumber* pageNumber;

@property(nonatomic) NSNumber* count;

@end
