#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPImages.h"
#import "ASPLink.h"
#import "ASPRectangle.h"


@protocol ASPPage
@end

@interface ASPPage : ASPObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) ASPImages* images;

@property(nonatomic) ASPRectangle* rectangle;

@property(nonatomic) NSArray<ASPLink>* links;

@end
