#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"
#import "ASPTextFormat.h"


@protocol ASPTextItem
@end

@interface ASPTextItem : ASPObject


@property(nonatomic) NSString* text;

@property(nonatomic) ASPTextFormat* format;

@property(nonatomic) NSArray<ASPLink>* links;

@end
