#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPColor.h"


@protocol ASPTextState
@end

@interface ASPTextState : ASPObject


@property(nonatomic) NSNumber* fontSize;

@property(nonatomic) NSString* font;

@property(nonatomic) ASPColor* foregroundColor;

@property(nonatomic) ASPColor* backgroundColor;

@property(nonatomic) NSString* fontStyle;

@end
