#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPTextReplace
@end

@interface ASPTextReplace : ASPObject


@property(nonatomic) NSString* oldValue;

@property(nonatomic) NSString* newerValue;

@property(nonatomic) NSNumber* regex;

@end
