#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPTextItem.h"
#import "ASPLink.h"


@protocol ASPTextItems
@end

@interface ASPTextItems : ASPObject


@property(nonatomic) NSArray<ASPTextItem>* list;

@property(nonatomic) NSArray<ASPLink>* links;

@end
