#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPPageWordCount.h"


@protocol ASPWordCount
@end

@interface ASPWordCount : ASPObject


@property(nonatomic) NSArray<ASPPageWordCount>* list;

@end
