<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class AnnotationsResponse {
	static $swaggerTypes = array(
		'Annotations' => 'Annotations',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Annotations; // Annotations
	public $Code; // string
	public $Status; // string
	}

