<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Annotation {
	static $swaggerTypes = array(
		'Color' => 'Color',
		'Contents' => 'string',
		'CreationDate' => 'string',
		'Subject' => 'string',
		'Title' => 'string',
		'Modified' => 'string',
		'Links' => 'array[Link]'

	);

	public $Color; // Color
	public $Contents; // string
	public $CreationDate; // string
	public $Subject; // string
	public $Title; // string
	public $Modified; // string
	public $Links; // array[Link]
	}

