<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Attachment {
	static $swaggerTypes = array(
		'Description' => 'string',
		'MimeType' => 'string',
		'Name' => 'string',
		'CreationDate' => 'string',
		'ModificationDate' => 'string',
		'Size' => 'int',
		'CheckSum' => 'string',
		'Links' => 'array[Link]'

	);

	public $Description; // string
	public $MimeType; // string
	public $Name; // string
	public $CreationDate; // string
	public $ModificationDate; // string
	public $Size; // int
	public $CheckSum; // string
	public $Links; // array[Link]
	}

