<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class AttachmentsResponse {
	static $swaggerTypes = array(
		'Attachments' => 'Attachments',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Attachments; // Attachments
	public $Code; // string
	public $Status; // string
	}

