<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class BookmarksResponse {
	static $swaggerTypes = array(
		'Bookmarks' => 'Bookmarks',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Bookmarks; // Bookmarks
	public $Code; // string
	public $Status; // string
	}

