<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Bookmarks {
	static $swaggerTypes = array(
		'List' => 'array[LinkElement]',
		'Links' => 'array[Link]'

	);

	public $List; // array[LinkElement]
	public $Links; // array[Link]
	}

