<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class DocumentProperty {
	static $swaggerTypes = array(
		'Name' => 'string',
		'Value' => 'string',
		'BuiltIn' => 'bool',
		'Links' => 'array[Link]'

	);

	public $Name; // string
	public $Value; // string
	public $BuiltIn; // bool
	public $Links; // array[Link]
	}

