<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class DocumentPropertyResponse {
	static $swaggerTypes = array(
		'DocumentProperty' => 'DocumentProperty',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $DocumentProperty; // DocumentProperty
	public $Code; // string
	public $Status; // string
	}

