<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class DocumentPagesResponse {
	static $swaggerTypes = array(
		'Pages' => 'Pages',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Pages; // Pages
	public $Code; // string
	public $Status; // string
	}

