<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Field {
	static $swaggerTypes = array(
		'Name' => 'string',
		'Type' => 'FieldType',
		'Values' => 'array[string]',
		'SelectedItems' => 'array[int]',
		'Rect' => 'Rectangle',
		'Links' => 'array[Link]'

	);

	public $Name; // string
	public $Type; // FieldType
	public $Values; // array[string]
	public $SelectedItems; // array[int]
	public $Rect; // Rectangle
	public $Links; // array[Link]
	}

