<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class FieldResponse {
	static $swaggerTypes = array(
		'Field' => 'Field',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Field; // Field
	public $Code; // string
	public $Status; // string
	}

