<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Image {
	static $swaggerTypes = array(
		'Width' => 'int',
		'Height' => 'int',
		'Links' => 'array[Link]'

	);

	public $Width; // int
	public $Height; // int
	public $Links; // array[Link]
	}

