<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class LinkAnnotationsResponse {
	static $swaggerTypes = array(
		'Links' => 'LinkAnnotations',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Links; // LinkAnnotations
	public $Code; // string
	public $Status; // string
	}

