<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class LinkAnnotation {
	static $swaggerTypes = array(
		'ActionType' => 'LinkActionType',
		'Action' => 'string',
		'Highlighting' => 'LinkHighlightingMode',
		'Color' => 'Color',
		'Links' => 'array[Link]'

	);

	public $ActionType; // LinkActionType
	public $Action; // string
	public $Highlighting; // LinkHighlightingMode
	public $Color; // Color
	public $Links; // array[Link]
	}

