<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Page {
	static $swaggerTypes = array(
		'Id' => 'int',
		'Images' => 'Images',
		'Rectangle' => 'Rectangle',
		'Links' => 'array[Link]'

	);

	public $Id; // int
	public $Images; // Images
	public $Rectangle; // Rectangle
	public $Links; // array[Link]
	}

