<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class PageWordCount {
	static $swaggerTypes = array(
		'PageNumber' => 'int',
		'Count' => 'int'

	);

	public $PageNumber; // int
	public $Count; // int
	}

