<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ResponseMessage {
	static $swaggerTypes = array(
		'Code' => 'int',
		'Message' => 'string'

	);

	public $Code; // int
	public $Message; // string
	}

