<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Signature {
	static $swaggerTypes = array(
		'SignaturePath' => 'string',
		'SignatureType' => 'string',
		'Password' => 'string',
		'Contact' => 'string',
		'Location' => 'string',
		'Visible' => 'bool',
		'Rectangle' => 'Rectangle',
		'FormFieldName' => 'string',
		'Authority' => 'string',
		'Date' => 'string'

	);

	public $SignaturePath; // string
	public $SignatureType; // string
	public $Password; // string
	public $Contact; // string
	public $Location; // string
	public $Visible; // bool
	public $Rectangle; // Rectangle
	public $FormFieldName; // string
	public $Authority; // string
	public $Date; // string
	}

