<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SplitResultResponse {
	static $swaggerTypes = array(
		'Result' => 'SplitResult',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Result; // SplitResult
	public $Code; // string
	public $Status; // string
	}

