<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TextFormat {
	static $swaggerTypes = array(
		'Color' => 'Color',
		'FontSize' => 'float',
		'FontName' => 'string',
		'Links' => 'array[Link]'

	);

	public $Color; // Color
	public $FontSize; // float
	public $FontName; // string
	public $Links; // array[Link]
	}

