<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TextFormatResponse {
	static $swaggerTypes = array(
		'TextFormat' => 'TextFormat',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $TextFormat; // TextFormat
	public $Code; // string
	public $Status; // string
	}

