<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TextReplaceListRequest {
	static $swaggerTypes = array(
		'TextReplaces' => 'array[TextReplace]'

	);

	public $TextReplaces; // array[TextReplace]
	}

