<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TextItemsResponse {
	static $swaggerTypes = array(
		'TextItems' => 'TextItems',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $TextItems; // TextItems
	public $Code; // string
	public $Status; // string
	}

