<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TextState {
	static $swaggerTypes = array(
		'FontSize' => 'float',
		'Font' => 'string',
		'ForegroundColor' => 'Color',
		'BackgroundColor' => 'Color',
		'FontStyle' => 'FontStyles'

	);

	public $FontSize; // float
	public $Font; // string
	public $ForegroundColor; // Color
	public $BackgroundColor; // Color
	public $FontStyle; // FontStyles
	}

