<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TextItem {
	static $swaggerTypes = array(
		'Text' => 'string',
		'Format' => 'TextFormat',
		'Links' => 'array[Link]'

	);

	public $Text; // string
	public $Format; // TextFormat
	public $Links; // array[Link]
	}

