#!/usr/bin/env python

class Document(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'DocumentProperties': 'DocumentProperties',
            'Pages': 'Pages',
            'Links': 'list[Link]'

        }

        self.attributeMap = {
            'DocumentProperties': 'DocumentProperties','Pages': 'Pages','Links': 'Links'}       

        self.DocumentProperties = None # DocumentProperties
        self.Pages = None # Pages
        self.Links = None # list[Link]
        
