#!/usr/bin/env python

class Rectangle(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'X': 'int',
            'Y': 'int',
            'Width': 'int',
            'Height': 'int'

        }

        self.attributeMap = {
            'X': 'X','Y': 'Y','Width': 'Width','Height': 'Height'}       

        self.X = None # int
        self.Y = None # int
        self.Width = None # int
        self.Height = None # int
        
