#!/usr/bin/env python

class TextState(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'FontSize': 'float',
            'Font': 'str',
            'ForegroundColor': 'Color',
            'BackgroundColor': 'Color',
            'FontStyle': 'FontStyles'

        }

        self.attributeMap = {
            'FontSize': 'FontSize','Font': 'Font','ForegroundColor': 'ForegroundColor','BackgroundColor': 'BackgroundColor','FontStyle': 'FontStyle'}       

        self.FontSize = None # float
        self.Font = None # str
        self.ForegroundColor = None # Color
        self.BackgroundColor = None # Color
        self.FontStyle = None # FontStyles
        
