<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ImageResponse {
	static $swaggerTypes = array(
		'Image' => 'Image',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Image; // Image
	public $Code; // string
	public $Status; // string
	}

