<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Rectangle {
	static $swaggerTypes = array(
		'X' => 'int',
		'Y' => 'int',
		'Width' => 'int',
		'Height' => 'int'

	);

	public $X; // int
	public $Y; // int
	public $Width; // int
	public $Height; // int
	}

