<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SplitResultDocument {
	static $swaggerTypes = array(
		'Id' => 'int',
		'Href' => 'string',
		'Rel' => 'string',
		'Type' => 'string',
		'Title' => 'string'

	);

	public $Id; // int
	public $Href; // string
	public $Rel; // string
	public $Type; // string
	public $Title; // string
	}

