<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TextReplace {
	static $swaggerTypes = array(
		'OldValue' => 'string',
		'NewValue' => 'string',
		'Regex' => 'bool'

	);

	public $OldValue; // string
	public $NewValue; // string
	public $Regex; // bool
	}

