#!/usr/bin/env python

class Annotation(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Color': 'Color',
            'Contents': 'str',
            'CreationDate': 'str',
            'Subject': 'str',
            'Title': 'str',
            'Modified': 'str',
            'Links': 'list[Link]'

        }

        self.attributeMap = {
            'Color': 'Color','Contents': 'Contents','CreationDate': 'CreationDate','Subject': 'Subject','Title': 'Title','Modified': 'Modified','Links': 'Links'}       

        self.Color = None # Color
        self.Contents = None # str
        self.CreationDate = None # str
        self.Subject = None # str
        self.Title = None # str
        self.Modified = None # str
        self.Links = None # list[Link]
        
