#!/usr/bin/env python

class AppendDocument(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Document': 'str',
            'StartPage': 'int',
            'EndPage': 'int'

        }

        self.attributeMap = {
            'Document': 'Document','StartPage': 'StartPage','EndPage': 'EndPage'}       

        self.Document = None # str
        self.StartPage = None # int
        self.EndPage = None # int
        
