#!/usr/bin/env python

class Color(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'A': 'int',
            'R': 'int',
            'G': 'int',
            'B': 'int'

        }

        self.attributeMap = {
            'A': 'A','R': 'R','G': 'G','B': 'B'}       

        self.A = None # int
        self.R = None # int
        self.G = None # int
        self.B = None # int
        
