#!/usr/bin/env python

class Image(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Width': 'int',
            'Height': 'int',
            'Links': 'list[Link]'

        }

        self.attributeMap = {
            'Width': 'Width','Height': 'Height','Links': 'Links'}       

        self.Width = None # int
        self.Height = None # int
        self.Links = None # list[Link]
        
