#!/usr/bin/env python

class Images(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'List': 'list[Image]',
            'Links': 'list[Link]'

        }

        self.attributeMap = {
            'List': 'List','Links': 'Links'}       

        self.List = None # list[Image]
        self.Links = None # list[Link]
        
