#!/usr/bin/env python

class LinkAnnotation(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'ActionType': 'int',
            'Action': 'str',
            'Highlighting': 'LinkHighlightingMode',
            'Color': 'Color',
            'Links': 'list[Link]'

        }

        self.attributeMap = {
            'ActionType': 'ActionType','Action': 'Action','Highlighting': 'Highlighting','Color': 'Color','Links': 'Links'}       

        self.ActionType = None # LinkActionType
        self.Action = None # str
        self.Highlighting = None # LinkHighlightingMode
        self.Color = None # Color
        self.Links = None # list[Link]
        
