#!/usr/bin/env python

class Signature(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'SignaturePath': 'str',
            'SignatureType': 'str',
            'Password': 'str',
            'Contact': 'str',
            'Location': 'str',
            'Visible': 'bool',
            'Rectangle': 'Rectangle',
            'FormFieldName': 'str',
            'Authority': 'str',
            'Date': 'str'

        }

        self.attributeMap = {
            'SignaturePath': 'SignaturePath','SignatureType': 'SignatureType','Password': 'Password','Contact': 'Contact','Location': 'Location','Visible': 'Visible','Rectangle': 'Rectangle','FormFieldName': 'FormFieldName','Authority': 'Authority','Date': 'Date'}       

        self.SignaturePath = None # str
        self.SignatureType = None # str
        self.Password = None # str
        self.Contact = None # str
        self.Location = None # str
        self.Visible = None # bool
        self.Rectangle = None # Rectangle
        self.FormFieldName = None # str
        self.Authority = None # str
        self.Date = None # str
        
