#!/usr/bin/env python

class SplitResultDocument(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Id': 'int',
            'Href': 'str',
            'Rel': 'str',
            'Type': 'str',
            'Title': 'str'

        }

        self.attributeMap = {
            'Id': 'Id','Href': 'Href','Rel': 'Rel','Type': 'Type','Title': 'Title'}       

        self.Id = None # int
        self.Href = None # str
        self.Rel = None # str
        self.Type = None # str
        self.Title = None # str
        
