#!/usr/bin/env python

class Stamp(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Type': 'StampType',
            'Background': 'bool',
            'BottomMargin': 'float',
            'HorizontalAlignment': 'HorizontalAlignment',
            'LeftMargin': 'float',
            'Opacity': 'float',
            'RightMargin': 'float',
            'Rotate': 'Rotation',
            'RotateAngle': 'float',
            'TopMargin': 'float',
            'VerticalAlignment': 'VerticalAlignment',
            'XIndent': 'float',
            'YIndent': 'float',
            'Zoom': 'float',
            'TextAlignment': 'HorizontalAlignment',
            'Value': 'str',
            'TextState': 'TextState',
            'FileName': 'str',
            'Width': 'float',
            'Height': 'float',
            'PageIndex': 'int',
            'StartingNumber': 'int'

        }

        self.attributeMap = {
            'Type': 'Type','Background': 'Background','BottomMargin': 'BottomMargin','HorizontalAlignment': 'HorizontalAlignment','LeftMargin': 'LeftMargin','Opacity': 'Opacity','RightMargin': 'RightMargin','Rotate': 'Rotate','RotateAngle': 'RotateAngle','TopMargin': 'TopMargin','VerticalAlignment': 'VerticalAlignment','XIndent': 'XIndent','YIndent': 'YIndent','Zoom': 'Zoom','TextAlignment': 'TextAlignment','Value': 'Value','TextState': 'TextState','FileName': 'FileName','Width': 'Width','Height': 'Height','PageIndex': 'PageIndex','StartingNumber': 'StartingNumber'}       

        self.Type = None # StampType
        self.Background = None # bool
        self.BottomMargin = None # float
        self.HorizontalAlignment = None # HorizontalAlignment
        self.LeftMargin = None # float
        self.Opacity = None # float
        self.RightMargin = None # float
        self.Rotate = None # Rotation
        self.RotateAngle = None # float
        self.TopMargin = None # float
        self.VerticalAlignment = None # VerticalAlignment
        self.XIndent = None # float
        self.YIndent = None # float
        self.Zoom = None # float
        self.TextAlignment = None # HorizontalAlignment
        self.Value = None # str
        self.TextState = None # TextState
        self.FileName = None # str
        self.Width = None # float
        self.Height = None # float
        self.PageIndex = None # int
        self.StartingNumber = None # int
        
