#!/usr/bin/env python

class TextFormat(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Color': 'Color',
            'FontSize': 'float',
            'FontName': 'str',
            'Links': 'list[Link]'

        }

        self.attributeMap = {
            'Color': 'Color','FontSize': 'FontSize','FontName': 'FontName','Links': 'Links'}       

        self.Color = None # Color
        self.FontSize = None # float
        self.FontName = None # str
        self.Links = None # list[Link]
        
