#!/usr/bin/env python

class Attachment(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Description': 'str',
            'MimeType': 'str',
            'Name': 'str',
            'CreationDate': 'str',
            'ModificationDate': 'str',
            'Size': 'int',
            'CheckSum': 'str',
            'Links': 'list[Link]'

        }

        self.attributeMap = {
            'Description': 'Description','MimeType': 'MimeType','Name': 'Name','CreationDate': 'CreationDate','ModificationDate': 'ModificationDate','Size': 'Size','CheckSum': 'CheckSum','Links': 'Links'}       

        self.Description = None # str
        self.MimeType = None # str
        self.Name = None # str
        self.CreationDate = None # str
        self.ModificationDate = None # str
        self.Size = None # int
        self.CheckSum = None # str
        self.Links = None # list[Link]
        
