#!/usr/bin/env python

class LinkAnnotationResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Link': 'LinkAnnotation',
            'Code': 'str',
            'Status': 'str'

        }

        self.attributeMap = {
            'Link': 'Link','Code': 'Code','Status': 'Status'}       

        self.Link = None # LinkAnnotation
        self.Code = None # str
        self.Status = None # str
        
