#!/usr/bin/env python

class Page(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Id': 'int',
            'Images': 'Images',
            'Rectangle': 'Rectangle',
            'Links': 'list[Link]'

        }

        self.attributeMap = {
            'Id': 'Id','Images': 'Images','Rectangle': 'Rectangle','Links': 'Links'}       

        self.Id = None # int
        self.Images = None # Images
        self.Rectangle = None # Rectangle
        self.Links = None # list[Link]
        
