#!/usr/bin/env python

class PageTextReplaceResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Page': 'Page',
            'Matches': 'int',
            'Code': 'str',
            'Status': 'str'

        }

        self.attributeMap = {
            'Page': 'Page','Matches': 'Matches','Code': 'Code','Status': 'Status'}       

        self.Page = None # Page
        self.Matches = None # int
        self.Code = None # str
        self.Status = None # str
        
