#!/usr/bin/env python

class TextReplace(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'OldValue': 'str',
            'NewValue': 'str',
            'Regex': 'bool'

        }

        self.attributeMap = {
            'OldValue': 'OldValue','NewValue': 'NewValue','Regex': 'Regex'}       

        self.OldValue = None # str
        self.NewValue = None # str
        self.Regex = None # bool
        
