#!/usr/bin/env python

class TiffExportOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Brightness': 'float',
            'Compression': 'str',
            'ColorDepth': 'str',
            'LeftMargin': 'int',
            'RightMargin': 'int',
            'TopMargin': 'int',
            'BottomMargin': 'int',
            'Orientation': 'str',
            'SkipBlankPages': 'bool',
            'Width': 'int',
            'Height': 'int',
            'XResolution': 'int',
            'YResolution': 'int',
            'PageIndex': 'int',
            'PageCount': 'int',
            'ResultFile': 'str'

        }

        self.attributeMap = {
            'Brightness': 'Brightness','Compression': 'Compression','ColorDepth': 'ColorDepth','LeftMargin': 'LeftMargin','RightMargin': 'RightMargin','TopMargin': 'TopMargin','BottomMargin': 'BottomMargin','Orientation': 'Orientation','SkipBlankPages': 'SkipBlankPages','Width': 'Width','Height': 'Height','XResolution': 'XResolution','YResolution': 'YResolution','PageIndex': 'PageIndex','PageCount': 'PageCount','ResultFile': 'ResultFile'}       

        self.Brightness = None # float
        self.Compression = None # str
        self.ColorDepth = None # str
        self.LeftMargin = None # int
        self.RightMargin = None # int
        self.TopMargin = None # int
        self.BottomMargin = None # int
        self.Orientation = None # str
        self.SkipBlankPages = None # bool
        self.Width = None # int
        self.Height = None # int
        self.XResolution = None # int
        self.YResolution = None # int
        self.PageIndex = None # int
        self.PageCount = None # int
        self.ResultFile = None # str
        
