#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"


@protocol ASPAttachment
@end

@interface ASPAttachment : ASPObject


@property(nonatomic) NSString* _description;

@property(nonatomic) NSString* mimeType;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* creationDate;

@property(nonatomic) NSString* modificationDate;

@property(nonatomic) NSNumber* size;

@property(nonatomic) NSString* checkSum;

@property(nonatomic) NSArray<ASPLink>* links;

@end
