#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPColor
@end

@interface ASPColor : ASPObject


@property(nonatomic) NSString* A;

@property(nonatomic) NSString* R;

@property(nonatomic) NSString* G;

@property(nonatomic) NSString* B;

@end
