#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPField.h"
#import "ASPLink.h"


@protocol ASPFields
@end

@interface ASPFields : ASPObject


@property(nonatomic) NSArray<ASPField>* list;

@property(nonatomic) NSArray<ASPLink>* links;

@end
