#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPLink
@end

@interface ASPLink : ASPObject


@property(nonatomic) NSString* href;

@property(nonatomic) NSString* rel;

@property(nonatomic) NSString* type;

@property(nonatomic) NSString* title;

@end
