#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"
#import "ASPColor.h"


@protocol ASPLinkAnnotation
@end

@interface ASPLinkAnnotation : ASPObject


@property(nonatomic) NSString* actionType;

@property(nonatomic) NSString* action;

@property(nonatomic) NSString* highlighting;

@property(nonatomic) ASPColor* color;

@property(nonatomic) NSArray<ASPLink>* links;

@end
