#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPRectangle
@end

@interface ASPRectangle : ASPObject

/* The x coord [optional]
 */
@property(nonatomic) NSNumber* X;
/* The y coord [optional]
 */
@property(nonatomic) NSNumber* Y;
/* The width [optional]
 */
@property(nonatomic) NSNumber* width;
/* The height [optional]
 */
@property(nonatomic) NSNumber* height;

@end
