#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPTextState.h"


@protocol ASPStamp
@end

@interface ASPStamp : ASPObject


@property(nonatomic) NSString* type;

@property(nonatomic) NSNumber* background;

@property(nonatomic) NSNumber* bottomMargin;

@property(nonatomic) NSString* horizontalAlignment;

@property(nonatomic) NSNumber* leftMargin;

@property(nonatomic) NSNumber* opacity;

@property(nonatomic) NSNumber* rightMargin;

@property(nonatomic) NSString* rotate;

@property(nonatomic) NSNumber* rotateAngle;

@property(nonatomic) NSNumber* topMargin;

@property(nonatomic) NSString* verticalAlignment;

@property(nonatomic) NSNumber* xIndent;

@property(nonatomic) NSNumber* yIndent;

@property(nonatomic) NSNumber* zoom;

@property(nonatomic) NSString* textAlignment;

@property(nonatomic) NSString* value;

@property(nonatomic) ASPTextState* textState;

@property(nonatomic) NSString* fileName;

@property(nonatomic) NSNumber* width;

@property(nonatomic) NSNumber* height;

@property(nonatomic) NSNumber* pageIndex;

@property(nonatomic) NSNumber* startingNumber;

@end
