<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class AppendDocument {
	static $swaggerTypes = array(
		'Document' => 'string',
		'StartPage' => 'int',
		'EndPage' => 'int'

	);

	public $Document; // string
	public $StartPage; // int
	public $EndPage; // int
	}

