<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class AttachmentResponse {
	static $swaggerTypes = array(
		'Attachment' => 'Attachment',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Attachment; // Attachment
	public $Code; // string
	public $Status; // string
	}

