<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Color {
	static $swaggerTypes = array(
		'A' => 'integer',
		'R' => 'integer',
		'G' => 'integer',
		'B' => 'integer'

	);

	public $A; // integer
	public $R; // integer
	public $G; // integer
	public $B; // integer
	}

