<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class DocumentResponse {
	static $swaggerTypes = array(
		'Document' => 'Document',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Document; // Document
	public $Code; // string
	public $Status; // string
	}

