<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Document {
	static $swaggerTypes = array(
		'DocumentProperties' => 'DocumentProperties',
		'Pages' => 'Pages',
		'Links' => 'array[Link]'

	);

	public $DocumentProperties; // DocumentProperties
	public $Pages; // Pages
	public $Links; // array[Link]
	}

