<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ImagesResponse {
	static $swaggerTypes = array(
		'Images' => 'Images',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Images; // Images
	public $Code; // string
	public $Status; // string
	}

