<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class LinkAnnotationResponse {
	static $swaggerTypes = array(
		'Link' => 'LinkAnnotation',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Link; // LinkAnnotation
	public $Code; // string
	public $Status; // string
	}

