<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class LinkElement {
	static $swaggerTypes = array(
		'Links' => 'array[Link]'

	);

	public $Links; // array[Link]
	}

