<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class MergeDocuments {
	static $swaggerTypes = array(
		'List' => 'array[string]'

	);

	public $List; // array[string]
	}

