<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class PageTextReplaceResponse {
	static $swaggerTypes = array(
		'Page' => 'Page',
		'Matches' => 'int',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Page; // Page
	public $Matches; // int
	public $Code; // string
	public $Status; // string
	}

