<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SplitResult {
	static $swaggerTypes = array(
		'Documents' => 'array[SplitResultDocument]'

	);

	public $Documents; // array[SplitResultDocument]
	}

