<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Stamp {
	static $swaggerTypes = array(
		'Type' => 'StampType',
		'Background' => 'bool',
		'BottomMargin' => 'float',
		'HorizontalAlignment' => 'HorizontalAlignment',
		'LeftMargin' => 'float',
		'Opacity' => 'float',
		'RightMargin' => 'float',
		'Rotate' => 'Rotation',
		'RotateAngle' => 'float',
		'TopMargin' => 'float',
		'VerticalAlignment' => 'VerticalAlignment',
		'XIndent' => 'float',
		'YIndent' => 'float',
		'Zoom' => 'float',
		'TextAlignment' => 'HorizontalAlignment',
		'Value' => 'string',
		'TextState' => 'TextState',
		'FileName' => 'string',
		'Width' => 'float',
		'Height' => 'float',
		'PageIndex' => 'int',
		'StartingNumber' => 'int'

	);

	public $Type; // StampType
	public $Background; // bool
	public $BottomMargin; // float
	public $HorizontalAlignment; // HorizontalAlignment
	public $LeftMargin; // float
	public $Opacity; // float
	public $RightMargin; // float
	public $Rotate; // Rotation
	public $RotateAngle; // float
	public $TopMargin; // float
	public $VerticalAlignment; // VerticalAlignment
	public $XIndent; // float
	public $YIndent; // float
	public $Zoom; // float
	public $TextAlignment; // HorizontalAlignment
	public $Value; // string
	public $TextState; // TextState
	public $FileName; // string
	public $Width; // float
	public $Height; // float
	public $PageIndex; // int
	public $StartingNumber; // int
	}

