<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TextItemResponse {
	static $swaggerTypes = array(
		'TextItem' => 'TextItem',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $TextItem; // TextItem
	public $Code; // string
	public $Status; // string
	}

