<?php
namespace Aspose\PDF\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TiffExportOptions {
	static $swaggerTypes = array(
		'Brightness' => 'float',
		'Compression' => 'string',
		'ColorDepth' => 'string',
		'LeftMargin' => 'int',
		'RightMargin' => 'int',
		'TopMargin' => 'int',
		'BottomMargin' => 'int',
		'Orientation' => 'string',
		'SkipBlankPages' => 'bool',
		'Width' => 'int',
		'Height' => 'int',
		'XResolution' => 'int',
		'YResolution' => 'int',
		'PageIndex' => 'int',
		'PageCount' => 'int',
		'ResultFile' => 'string'

	);

	public $Brightness; // float
	public $Compression; // string
	public $ColorDepth; // string
	public $LeftMargin; // int
	public $RightMargin; // int
	public $TopMargin; // int
	public $BottomMargin; // int
	public $Orientation; // string
	public $SkipBlankPages; // bool
	public $Width; // int
	public $Height; // int
	public $XResolution; // int
	public $YResolution; // int
	public $PageIndex; // int
	public $PageCount; // int
	public $ResultFile; // string
	}

